更改

diff --git a/.github/workflows/prettier.yml b/.github/workflows/prettier.yml
--- a/.github/workflows/prettier.yml
+++ b/.github/workflows/prettier.yml
@@ -19,8 +19,8 @@ jobs:
         uses: actions/checkout@v4
       - name: Setup Node.js ⚙️
         uses: actions/setup-node@v4
-      - name: Install Prettier 💾
-        run: npm install --save-dev --save-exact prettier @shopify/prettier-plugin-liquid
+      - name: Install dependencies 💾
+        run: npm ci
       - name: Prettier Check 🔎
         id: prettier
         run: npx prettier . --check
@@ -29,20 +29,23 @@ jobs:
         if: ${{ failure() }}
         run: |
           npx prettier . --write
-          git diff -- . ':(exclude)package-lock.json' ':(exclude)package.json' > diff.txt
-          npm install -g diff2html-cli
-          diff2html -i file -s side -F diff.html -- diff.txt
+          git diff > diff.txt
+          # exit with error if diff is not empty
+          if [ -s diff.txt ]; then
+            echo "Code style issues found. Please run 'npm run format' and commit the changes."
+            exit 1
+          fi
       - name: Upload html diff ⬆️
-        id: artifact-upload
+        # https://docs.github.com/en/actions/learn-github-actions/expressions#failure
         if: ${{ failure() && steps.prettier.conclusion == 'failure' }}
         uses: actions/upload-artifact@v4
         with:
-          name: HTML Diff
+          name: prettier-diff
           path: diff.html
-          retention-days: 7
       - name: Dispatch information to repository 🗣️
         if: ${{ failure() && steps.prettier.conclusion == 'failure' && github.event_name == 'pull_request' }}
-        uses: peter-evans/repository-dispatch@v2
+        uses: peter-evans/repository-dispatch@v3
         with:
+          token: ${{ secrets.PAT }}
           event-type: prettier-failed-on-pr
-          client-payload: '{"pr_number": "${{ github.event.number }}", "artifact_url": "${{ steps.artifact-upload.outputs.artifact-url }}", "run_id": "${{ github.run_id }}"}'
+          client-payload: '{{ "pr_number": ${{ github.event.pull_request.number }}, "run_id": ${{ github.run_id }}, "artifact_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload.outputs.artifact-id }}" }}'
